buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:9.3.1'
    }
}

allprojects {
    project.group = 'com.github.mobialia'
    project.version = '0.9.6'

    repositories {
        maven { url 'https://jitpack.io' }
        google()
        mavenCentral()
    }
}