apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

base {
    archivesName = 'jmini3d-android'
}

dependencies {
    api project(':core')
}

android {
    namespace 'jmini3d.android'
    compileSdk 37

    defaultConfig {
        targetSdk 37
        minSdk 21
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
        }
    }
}

tasks.register('copyResources', Copy)

copyResources {
    from '../core/shaders'
    into 'src/main/res/raw'
    include('**/*')
}

preBuild.dependsOn copyResources

publishing {
    publications {
        jmini3dAndroid(MavenPublication) {
            artifactId = 'jmini3d-android'

            afterEvaluate {
                from components.release
            }
        }
    }
}
