apply plugin: 'com.android.application'

dependencies {
    implementation project(':core')
    implementation project(':android')
    implementation project(':demo-common')
}

android {
    compileSdk 37

    defaultConfig {
        versionCode 1
        versionName "1.0"

        minSdk 21
    }
    namespace 'jmini3d.android.demo'
    lint {
        abortOnError false
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

tasks.register('copyResources', Copy)

copyResources {
    from '../demo-common/resources'
    into 'src/main/res/drawable-nodpi'
    include('**/*')
}

preBuild.dependsOn copyResources
