apply plugin: 'java'
apply plugin: 'maven-publish'

base {
    archivesName = 'jmini3d-utils'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.register('sourcesJar', Jar) {
    dependsOn classes
    archiveClassifier = 'sources'
    from sourceSets.main.allSource
}

artifacts {
    archives sourcesJar
}

publishing {
    publications {
        jmini3dCore(MavenPublication) {
            from components.java
            artifactId = 'jmini3d-utils'
            artifact sourcesJar
        }
    }
}
